import { Pet } from "./Pet";
import { Model, Relation } from "#imports";
import type { MapModelOptions } from "vue-orm.js";

export class User extends Model {
  static override entity = "User";

  static override map(data: MapModelOptions<User>) {
    return {
      ...data,
      autoGeneratedID: (Math.random() * 100).toFixed(0),
    };
  }

  static override relations(): Record<string, Relation<any>> {
    return {
      pets: Relation.hasMany(Pet, "user_id"),
    };
  }

  declare id: string;
  declare firstname: string;
  declare lastname: string;

  get fullName() {
    return `${this.firstname || ""} ${this.lastname || ""}`;
  }
}

export class UserRepository extends Repository<User> {
  override use = User;
}
